### ISSUE TITLE
Vite manifest not found at: E:\LARAVEL\laravel-stisla\public\build/manifest.json

### ISSUE THREAD

**Issue by cahyadi16** [edikurniawan-dev/laravel-stisla#1]
terjadi error compile saat menggunakan laravel v.9.32.0 yang menggunakan vite.js karna pada version dibawah 9.18 itu menggunakan webpack..mix.js

mohon bantuannya

**Comment by RidoneMuh** [comment]
ganti aja mas dari vite ke mix, saya juga dulu masalah nya ini

**Comment by cahyadi16** [comment]
oke terima kasih mas
